status = [ "build:%" ]
block-labels = [ "S-wip", "S-nomerge" ]
pr-status = [
    "check: Validate PR title",
]

delete-merged-branches = true
timeout-sec = 7200 # two hours

cut-body-after = "\n<!-- Boilerplate:start -->" # see PULL_REQUEST_TEMPLATE.md

## [NOTE] (aseipp): these can't be enabled because you can't self-review or
## self-approve things you're a codeowner of, and bors does not like that...

# required-approvals = 1
# use-codeowners = true

## [NOTE] (aseipp): squash merge would be nice, but unfortunately it does
## nuke any GPG signatures you might have (somewhat annoying), but it also
## leaves the signed-off-by lines as well, which is what I really hate; in
## theory bors should be able to do this all on its own properly, but...
## sigh...

use-squash-merge = true
