name: Continuous Integration

on:
  push:
    branches: [ main, trying, staging ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "build: Full build and integrated tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: nix build
      - name: Check
        run: |
          nix flake check
          nix run
