name: PR Validation

on:
  # needs read/write GH token, do *not* execute arbitrary code from PR
  pull_request_target:
    types: [opened, edited]

jobs:
  check-pr:
    name: "check: Validate PR messages"
    runs-on: ubuntu-latest
    steps:
      - name: "Run validation script"
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            console.log('Title:', pr.title);

            if (!/^(feat|fix|doc|style|refactor|test|chore|perf): .*[^.]$/.test(pr.title)) {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: 'REQUEST_CHANGES',
                body: 'Invalid commit message format.'
              });
              await core.setFailed('Failing CI check due to bad message');
            } else {
              await github.rest.pulls.createReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                event: 'APPROVE',
              });
            }
